# Generated by Django 5.2 on 2025-10-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='article.articleadditionalinformation'),
        ),
    ]
